// Generated by gencpp from file grinder_scheduler/MapPreviewMetadata.msg
// DO NOT EDIT!


#ifndef GRINDER_SCHEDULER_MESSAGE_MAPPREVIEWMETADATA_H
#define GRINDER_SCHEDULER_MESSAGE_MAPPREVIEWMETADATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>

namespace grinder_scheduler
{
template <class ContainerAllocator>
struct MapPreviewMetadata_
{
  typedef MapPreviewMetadata_<ContainerAllocator> Type;

  MapPreviewMetadata_()
    : header()
    , map_version(0)
    , width(0)
    , height(0)
    , resolution(0.0)
    , origin()
    , frame_id()  {
    }
  MapPreviewMetadata_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , map_version(0)
    , width(0)
    , height(0)
    , resolution(0.0)
    , origin(_alloc)
    , frame_id(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _map_version_type;
  _map_version_type map_version;

   typedef uint32_t _width_type;
  _width_type width;

   typedef uint32_t _height_type;
  _height_type height;

   typedef float _resolution_type;
  _resolution_type resolution;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _origin_type;
  _origin_type origin;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _frame_id_type;
  _frame_id_type frame_id;





  typedef boost::shared_ptr< ::grinder_scheduler::MapPreviewMetadata_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grinder_scheduler::MapPreviewMetadata_<ContainerAllocator> const> ConstPtr;

}; // struct MapPreviewMetadata_

typedef ::grinder_scheduler::MapPreviewMetadata_<std::allocator<void> > MapPreviewMetadata;

typedef boost::shared_ptr< ::grinder_scheduler::MapPreviewMetadata > MapPreviewMetadataPtr;
typedef boost::shared_ptr< ::grinder_scheduler::MapPreviewMetadata const> MapPreviewMetadataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grinder_scheduler::MapPreviewMetadata_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grinder_scheduler::MapPreviewMetadata_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::grinder_scheduler::MapPreviewMetadata_<ContainerAllocator1> & lhs, const ::grinder_scheduler::MapPreviewMetadata_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.map_version == rhs.map_version &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height &&
    lhs.resolution == rhs.resolution &&
    lhs.origin == rhs.origin &&
    lhs.frame_id == rhs.frame_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::grinder_scheduler::MapPreviewMetadata_<ContainerAllocator1> & lhs, const ::grinder_scheduler::MapPreviewMetadata_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace grinder_scheduler

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::grinder_scheduler::MapPreviewMetadata_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grinder_scheduler::MapPreviewMetadata_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grinder_scheduler::MapPreviewMetadata_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grinder_scheduler::MapPreviewMetadata_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grinder_scheduler::MapPreviewMetadata_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grinder_scheduler::MapPreviewMetadata_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grinder_scheduler::MapPreviewMetadata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "48758f15fb7527a0ea9d6aed393eee0c";
  }

  static const char* value(const ::grinder_scheduler::MapPreviewMetadata_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x48758f15fb7527a0ULL;
  static const uint64_t static_value2 = 0xea9d6aed393eee0cULL;
};

template<class ContainerAllocator>
struct DataType< ::grinder_scheduler::MapPreviewMetadata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grinder_scheduler/MapPreviewMetadata";
  }

  static const char* value(const ::grinder_scheduler::MapPreviewMetadata_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grinder_scheduler::MapPreviewMetadata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"uint32 map_version\n"
"uint32 width\n"
"uint32 height\n"
"float32 resolution\n"
"geometry_msgs/Pose origin\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::grinder_scheduler::MapPreviewMetadata_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grinder_scheduler::MapPreviewMetadata_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.map_version);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.resolution);
      stream.next(m.origin);
      stream.next(m.frame_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MapPreviewMetadata_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grinder_scheduler::MapPreviewMetadata_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grinder_scheduler::MapPreviewMetadata_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "map_version: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.map_version);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "width: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.width);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "height: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.height);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "resolution: ";
    Printer<float>::stream(s, indent + "  ", v.resolution);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "origin: ";
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.origin);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.frame_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRINDER_SCHEDULER_MESSAGE_MAPPREVIEWMETADATA_H
