// Generated by gencpp from file grinder_scheduler/SchedulerStatus.msg
// DO NOT EDIT!


#ifndef GRINDER_SCHEDULER_MESSAGE_SCHEDULERSTATUS_H
#define GRINDER_SCHEDULER_MESSAGE_SCHEDULERSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose2D.h>

namespace grinder_scheduler
{
template <class ContainerAllocator>
struct SchedulerStatus_
{
  typedef SchedulerStatus_<ContainerAllocator> Type;

  SchedulerStatus_()
    : header()
    , task_id()
    , state()
    , progress(0.0)
    , map_version(0)
    , map_available(false)
    , stream_online(false)
    , replan_requested(false)
    , last_error()
    , pose()
    , path_point_count(0)  {
    }
  SchedulerStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , task_id(_alloc)
    , state(_alloc)
    , progress(0.0)
    , map_version(0)
    , map_available(false)
    , stream_online(false)
    , replan_requested(false)
    , last_error(_alloc)
    , pose(_alloc)
    , path_point_count(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _task_id_type;
  _task_id_type task_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _state_type;
  _state_type state;

   typedef float _progress_type;
  _progress_type progress;

   typedef uint32_t _map_version_type;
  _map_version_type map_version;

   typedef uint8_t _map_available_type;
  _map_available_type map_available;

   typedef uint8_t _stream_online_type;
  _stream_online_type stream_online;

   typedef uint8_t _replan_requested_type;
  _replan_requested_type replan_requested;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _last_error_type;
  _last_error_type last_error;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef uint32_t _path_point_count_type;
  _path_point_count_type path_point_count;





  typedef boost::shared_ptr< ::grinder_scheduler::SchedulerStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grinder_scheduler::SchedulerStatus_<ContainerAllocator> const> ConstPtr;

}; // struct SchedulerStatus_

typedef ::grinder_scheduler::SchedulerStatus_<std::allocator<void> > SchedulerStatus;

typedef boost::shared_ptr< ::grinder_scheduler::SchedulerStatus > SchedulerStatusPtr;
typedef boost::shared_ptr< ::grinder_scheduler::SchedulerStatus const> SchedulerStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grinder_scheduler::SchedulerStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grinder_scheduler::SchedulerStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::grinder_scheduler::SchedulerStatus_<ContainerAllocator1> & lhs, const ::grinder_scheduler::SchedulerStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.task_id == rhs.task_id &&
    lhs.state == rhs.state &&
    lhs.progress == rhs.progress &&
    lhs.map_version == rhs.map_version &&
    lhs.map_available == rhs.map_available &&
    lhs.stream_online == rhs.stream_online &&
    lhs.replan_requested == rhs.replan_requested &&
    lhs.last_error == rhs.last_error &&
    lhs.pose == rhs.pose &&
    lhs.path_point_count == rhs.path_point_count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::grinder_scheduler::SchedulerStatus_<ContainerAllocator1> & lhs, const ::grinder_scheduler::SchedulerStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace grinder_scheduler

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::grinder_scheduler::SchedulerStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grinder_scheduler::SchedulerStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grinder_scheduler::SchedulerStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grinder_scheduler::SchedulerStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grinder_scheduler::SchedulerStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grinder_scheduler::SchedulerStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grinder_scheduler::SchedulerStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f4e9266173ca1d3c3829a5e19868d37";
  }

  static const char* value(const ::grinder_scheduler::SchedulerStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f4e9266173ca1d3ULL;
  static const uint64_t static_value2 = 0xc3829a5e19868d37ULL;
};

template<class ContainerAllocator>
struct DataType< ::grinder_scheduler::SchedulerStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grinder_scheduler/SchedulerStatus";
  }

  static const char* value(const ::grinder_scheduler::SchedulerStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grinder_scheduler::SchedulerStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"string task_id\n"
"string state\n"
"float32 progress\n"
"uint32 map_version\n"
"bool map_available\n"
"bool stream_online\n"
"bool replan_requested\n"
"string last_error\n"
"geometry_msgs/Pose2D pose\n"
"uint32 path_point_count\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::grinder_scheduler::SchedulerStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grinder_scheduler::SchedulerStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.task_id);
      stream.next(m.state);
      stream.next(m.progress);
      stream.next(m.map_version);
      stream.next(m.map_available);
      stream.next(m.stream_online);
      stream.next(m.replan_requested);
      stream.next(m.last_error);
      stream.next(m.pose);
      stream.next(m.path_point_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SchedulerStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grinder_scheduler::SchedulerStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grinder_scheduler::SchedulerStatus_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "task_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.task_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "progress: ";
    Printer<float>::stream(s, indent + "  ", v.progress);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "map_version: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.map_version);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "map_available: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.map_available);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "stream_online: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stream_online);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "replan_requested: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.replan_requested);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "last_error: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.last_error);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "path_point_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.path_point_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRINDER_SCHEDULER_MESSAGE_SCHEDULERSTATUS_H
