# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from grinder_chassis_driver/ChassisStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class ChassisStatus(genpy.Message):
  _md5sum = "332527d3d7aab4589bcc1f2c43bb82d4"
  _type = "grinder_chassis_driver/ChassisStatus"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
bool connected
bool enabled
uint16 work_mode
int16 disc_speed_target
int16 disc_speed_feedback
bool disc_enabled
uint16 disc_lift_state
bool light_enabled
uint32 consecutive_failures
string last_error

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','connected','enabled','work_mode','disc_speed_target','disc_speed_feedback','disc_enabled','disc_lift_state','light_enabled','consecutive_failures','last_error']
  _slot_types = ['std_msgs/Header','bool','bool','uint16','int16','int16','bool','uint16','bool','uint32','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,connected,enabled,work_mode,disc_speed_target,disc_speed_feedback,disc_enabled,disc_lift_state,light_enabled,consecutive_failures,last_error

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ChassisStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.connected is None:
        self.connected = False
      if self.enabled is None:
        self.enabled = False
      if self.work_mode is None:
        self.work_mode = 0
      if self.disc_speed_target is None:
        self.disc_speed_target = 0
      if self.disc_speed_feedback is None:
        self.disc_speed_feedback = 0
      if self.disc_enabled is None:
        self.disc_enabled = False
      if self.disc_lift_state is None:
        self.disc_lift_state = 0
      if self.light_enabled is None:
        self.light_enabled = False
      if self.consecutive_failures is None:
        self.consecutive_failures = 0
      if self.last_error is None:
        self.last_error = ''
    else:
      self.header = std_msgs.msg.Header()
      self.connected = False
      self.enabled = False
      self.work_mode = 0
      self.disc_speed_target = 0
      self.disc_speed_feedback = 0
      self.disc_enabled = False
      self.disc_lift_state = 0
      self.light_enabled = False
      self.consecutive_failures = 0
      self.last_error = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2BH2hBHBI().pack(_x.connected, _x.enabled, _x.work_mode, _x.disc_speed_target, _x.disc_speed_feedback, _x.disc_enabled, _x.disc_lift_state, _x.light_enabled, _x.consecutive_failures))
      _x = self.last_error
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 16
      (_x.connected, _x.enabled, _x.work_mode, _x.disc_speed_target, _x.disc_speed_feedback, _x.disc_enabled, _x.disc_lift_state, _x.light_enabled, _x.consecutive_failures,) = _get_struct_2BH2hBHBI().unpack(str[start:end])
      self.connected = bool(self.connected)
      self.enabled = bool(self.enabled)
      self.disc_enabled = bool(self.disc_enabled)
      self.light_enabled = bool(self.light_enabled)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.last_error = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.last_error = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2BH2hBHBI().pack(_x.connected, _x.enabled, _x.work_mode, _x.disc_speed_target, _x.disc_speed_feedback, _x.disc_enabled, _x.disc_lift_state, _x.light_enabled, _x.consecutive_failures))
      _x = self.last_error
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 16
      (_x.connected, _x.enabled, _x.work_mode, _x.disc_speed_target, _x.disc_speed_feedback, _x.disc_enabled, _x.disc_lift_state, _x.light_enabled, _x.consecutive_failures,) = _get_struct_2BH2hBHBI().unpack(str[start:end])
      self.connected = bool(self.connected)
      self.enabled = bool(self.enabled)
      self.disc_enabled = bool(self.disc_enabled)
      self.light_enabled = bool(self.light_enabled)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.last_error = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.last_error = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2BH2hBHBI = None
def _get_struct_2BH2hBHBI():
    global _struct_2BH2hBHBI
    if _struct_2BH2hBHBI is None:
        _struct_2BH2hBHBI = struct.Struct("<2BH2hBHBI")
    return _struct_2BH2hBHBI
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
