(cl:defpackage slamware_ros_sdk-srv
  (:use )
  (:export
   "RELOCALIZATIONREQUEST"
   "<RELOCALIZATIONREQUEST-REQUEST>"
   "RELOCALIZATIONREQUEST-REQUEST"
   "<RELOCALIZATIONREQUEST-RESPONSE>"
   "RELOCALIZATIONREQUEST-RESPONSE"
   "SYNCGETSTCM"
   "<SYNCGETSTCM-REQUEST>"
   "SYNCGETSTCM-REQUEST"
   "<SYNCGETSTCM-RESPONSE>"
   "SYNCGETSTCM-RESPONSE"
   "SYNCSETSTCM"
   "<SYNCSETSTCM-REQUEST>"
   "SYNCSETSTCM-REQUEST"
   "<SYNCSETSTCM-RESPONSE>"
   "SYNCSETSTCM-RESPONSE"
  ))

