// Generated by gencpp from file slamware_ros_sdk/RelocalizationRequestResponse.msg
// DO NOT EDIT!


#ifndef SLAMWARE_ROS_SDK_MESSAGE_RELOCALIZATIONREQUESTRESPONSE_H
#define SLAMWARE_ROS_SDK_MESSAGE_RELOCALIZATIONREQUESTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace slamware_ros_sdk
{
template <class ContainerAllocator>
struct RelocalizationRequestResponse_
{
  typedef RelocalizationRequestResponse_<ContainerAllocator> Type;

  RelocalizationRequestResponse_()
    : success(false)  {
    }
  RelocalizationRequestResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::slamware_ros_sdk::RelocalizationRequestResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slamware_ros_sdk::RelocalizationRequestResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RelocalizationRequestResponse_

typedef ::slamware_ros_sdk::RelocalizationRequestResponse_<std::allocator<void> > RelocalizationRequestResponse;

typedef boost::shared_ptr< ::slamware_ros_sdk::RelocalizationRequestResponse > RelocalizationRequestResponsePtr;
typedef boost::shared_ptr< ::slamware_ros_sdk::RelocalizationRequestResponse const> RelocalizationRequestResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slamware_ros_sdk::RelocalizationRequestResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slamware_ros_sdk::RelocalizationRequestResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::slamware_ros_sdk::RelocalizationRequestResponse_<ContainerAllocator1> & lhs, const ::slamware_ros_sdk::RelocalizationRequestResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::slamware_ros_sdk::RelocalizationRequestResponse_<ContainerAllocator1> & lhs, const ::slamware_ros_sdk::RelocalizationRequestResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace slamware_ros_sdk

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::slamware_ros_sdk::RelocalizationRequestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slamware_ros_sdk::RelocalizationRequestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slamware_ros_sdk::RelocalizationRequestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slamware_ros_sdk::RelocalizationRequestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamware_ros_sdk::RelocalizationRequestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamware_ros_sdk::RelocalizationRequestResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slamware_ros_sdk::RelocalizationRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::slamware_ros_sdk::RelocalizationRequestResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::slamware_ros_sdk::RelocalizationRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slamware_ros_sdk/RelocalizationRequestResponse";
  }

  static const char* value(const ::slamware_ros_sdk::RelocalizationRequestResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slamware_ros_sdk::RelocalizationRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"#response\n"
"bool success\n"
;
  }

  static const char* value(const ::slamware_ros_sdk::RelocalizationRequestResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slamware_ros_sdk::RelocalizationRequestResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RelocalizationRequestResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slamware_ros_sdk::RelocalizationRequestResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slamware_ros_sdk::RelocalizationRequestResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLAMWARE_ROS_SDK_MESSAGE_RELOCALIZATIONREQUESTRESPONSE_H
