// Generated by gencpp from file slamware_ros_sdk/RelocalizationRequest.msg
// DO NOT EDIT!


#ifndef SLAMWARE_ROS_SDK_MESSAGE_RELOCALIZATIONREQUEST_H
#define SLAMWARE_ROS_SDK_MESSAGE_RELOCALIZATIONREQUEST_H

#include <ros/service_traits.h>


#include <slamware_ros_sdk/RelocalizationRequestRequest.h>
#include <slamware_ros_sdk/RelocalizationRequestResponse.h>


namespace slamware_ros_sdk
{

struct RelocalizationRequest
{

typedef RelocalizationRequestRequest Request;
typedef RelocalizationRequestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RelocalizationRequest
} // namespace slamware_ros_sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::slamware_ros_sdk::RelocalizationRequest > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::slamware_ros_sdk::RelocalizationRequest&) { return value(); }
};

template<>
struct DataType< ::slamware_ros_sdk::RelocalizationRequest > {
  static const char* value()
  {
    return "slamware_ros_sdk/RelocalizationRequest";
  }

  static const char* value(const ::slamware_ros_sdk::RelocalizationRequest&) { return value(); }
};


// service_traits::MD5Sum< ::slamware_ros_sdk::RelocalizationRequestRequest> should match
// service_traits::MD5Sum< ::slamware_ros_sdk::RelocalizationRequest >
template<>
struct MD5Sum< ::slamware_ros_sdk::RelocalizationRequestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::slamware_ros_sdk::RelocalizationRequest >::value();
  }
  static const char* value(const ::slamware_ros_sdk::RelocalizationRequestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::slamware_ros_sdk::RelocalizationRequestRequest> should match
// service_traits::DataType< ::slamware_ros_sdk::RelocalizationRequest >
template<>
struct DataType< ::slamware_ros_sdk::RelocalizationRequestRequest>
{
  static const char* value()
  {
    return DataType< ::slamware_ros_sdk::RelocalizationRequest >::value();
  }
  static const char* value(const ::slamware_ros_sdk::RelocalizationRequestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::slamware_ros_sdk::RelocalizationRequestResponse> should match
// service_traits::MD5Sum< ::slamware_ros_sdk::RelocalizationRequest >
template<>
struct MD5Sum< ::slamware_ros_sdk::RelocalizationRequestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::slamware_ros_sdk::RelocalizationRequest >::value();
  }
  static const char* value(const ::slamware_ros_sdk::RelocalizationRequestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::slamware_ros_sdk::RelocalizationRequestResponse> should match
// service_traits::DataType< ::slamware_ros_sdk::RelocalizationRequest >
template<>
struct DataType< ::slamware_ros_sdk::RelocalizationRequestResponse>
{
  static const char* value()
  {
    return DataType< ::slamware_ros_sdk::RelocalizationRequest >::value();
  }
  static const char* value(const ::slamware_ros_sdk::RelocalizationRequestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SLAMWARE_ROS_SDK_MESSAGE_RELOCALIZATIONREQUEST_H
