// Generated by gencpp from file slamware_ros_sdk/SyncSetStcmRequest.msg
// DO NOT EDIT!


#ifndef SLAMWARE_ROS_SDK_MESSAGE_SYNCSETSTCMREQUEST_H
#define SLAMWARE_ROS_SDK_MESSAGE_SYNCSETSTCMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace slamware_ros_sdk
{
template <class ContainerAllocator>
struct SyncSetStcmRequest_
{
  typedef SyncSetStcmRequest_<ContainerAllocator> Type;

  SyncSetStcmRequest_()
    : mapfile()  {
    }
  SyncSetStcmRequest_(const ContainerAllocator& _alloc)
    : mapfile(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _mapfile_type;
  _mapfile_type mapfile;





  typedef boost::shared_ptr< ::slamware_ros_sdk::SyncSetStcmRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slamware_ros_sdk::SyncSetStcmRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SyncSetStcmRequest_

typedef ::slamware_ros_sdk::SyncSetStcmRequest_<std::allocator<void> > SyncSetStcmRequest;

typedef boost::shared_ptr< ::slamware_ros_sdk::SyncSetStcmRequest > SyncSetStcmRequestPtr;
typedef boost::shared_ptr< ::slamware_ros_sdk::SyncSetStcmRequest const> SyncSetStcmRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slamware_ros_sdk::SyncSetStcmRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slamware_ros_sdk::SyncSetStcmRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::slamware_ros_sdk::SyncSetStcmRequest_<ContainerAllocator1> & lhs, const ::slamware_ros_sdk::SyncSetStcmRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mapfile == rhs.mapfile;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::slamware_ros_sdk::SyncSetStcmRequest_<ContainerAllocator1> & lhs, const ::slamware_ros_sdk::SyncSetStcmRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace slamware_ros_sdk

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::slamware_ros_sdk::SyncSetStcmRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slamware_ros_sdk::SyncSetStcmRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slamware_ros_sdk::SyncSetStcmRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slamware_ros_sdk::SyncSetStcmRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamware_ros_sdk::SyncSetStcmRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamware_ros_sdk::SyncSetStcmRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slamware_ros_sdk::SyncSetStcmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a1fb0700a7732a0f727e4b828cc211b4";
  }

  static const char* value(const ::slamware_ros_sdk::SyncSetStcmRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa1fb0700a7732a0fULL;
  static const uint64_t static_value2 = 0x727e4b828cc211b4ULL;
};

template<class ContainerAllocator>
struct DataType< ::slamware_ros_sdk::SyncSetStcmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slamware_ros_sdk/SyncSetStcmRequest";
  }

  static const char* value(const ::slamware_ros_sdk::SyncSetStcmRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slamware_ros_sdk::SyncSetStcmRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#request\n"
"string mapfile\n"
;
  }

  static const char* value(const ::slamware_ros_sdk::SyncSetStcmRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slamware_ros_sdk::SyncSetStcmRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mapfile);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SyncSetStcmRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slamware_ros_sdk::SyncSetStcmRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slamware_ros_sdk::SyncSetStcmRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "mapfile: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.mapfile);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLAMWARE_ROS_SDK_MESSAGE_SYNCSETSTCMREQUEST_H
