// Generated by gencpp from file slamware_ros_sdk/SystemStatus.msg
// DO NOT EDIT!


#ifndef SLAMWARE_ROS_SDK_MESSAGE_SYSTEMSTATUS_H
#define SLAMWARE_ROS_SDK_MESSAGE_SYSTEMSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace slamware_ros_sdk
{
template <class ContainerAllocator>
struct SystemStatus_
{
  typedef SystemStatus_<ContainerAllocator> Type;

  SystemStatus_()
    : timestamp_ns(0)
    , status()  {
    }
  SystemStatus_(const ContainerAllocator& _alloc)
    : timestamp_ns(0)
    , status(_alloc)  {
  (void)_alloc;
    }



   typedef uint64_t _timestamp_ns_type;
  _timestamp_ns_type timestamp_ns;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::slamware_ros_sdk::SystemStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::slamware_ros_sdk::SystemStatus_<ContainerAllocator> const> ConstPtr;

}; // struct SystemStatus_

typedef ::slamware_ros_sdk::SystemStatus_<std::allocator<void> > SystemStatus;

typedef boost::shared_ptr< ::slamware_ros_sdk::SystemStatus > SystemStatusPtr;
typedef boost::shared_ptr< ::slamware_ros_sdk::SystemStatus const> SystemStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::slamware_ros_sdk::SystemStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::slamware_ros_sdk::SystemStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::slamware_ros_sdk::SystemStatus_<ContainerAllocator1> & lhs, const ::slamware_ros_sdk::SystemStatus_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp_ns == rhs.timestamp_ns &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::slamware_ros_sdk::SystemStatus_<ContainerAllocator1> & lhs, const ::slamware_ros_sdk::SystemStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace slamware_ros_sdk

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::slamware_ros_sdk::SystemStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::slamware_ros_sdk::SystemStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slamware_ros_sdk::SystemStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::slamware_ros_sdk::SystemStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamware_ros_sdk::SystemStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::slamware_ros_sdk::SystemStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::slamware_ros_sdk::SystemStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ccc1e4824af73d0a8de6d07224862f42";
  }

  static const char* value(const ::slamware_ros_sdk::SystemStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xccc1e4824af73d0aULL;
  static const uint64_t static_value2 = 0x8de6d07224862f42ULL;
};

template<class ContainerAllocator>
struct DataType< ::slamware_ros_sdk::SystemStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "slamware_ros_sdk/SystemStatus";
  }

  static const char* value(const ::slamware_ros_sdk::SystemStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::slamware_ros_sdk::SystemStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"uint64 timestamp_ns\n"
"string status\n"
;
  }

  static const char* value(const ::slamware_ros_sdk::SystemStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::slamware_ros_sdk::SystemStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp_ns);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SystemStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::slamware_ros_sdk::SystemStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::slamware_ros_sdk::SystemStatus_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "timestamp_ns: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp_ns);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SLAMWARE_ROS_SDK_MESSAGE_SYSTEMSTATUS_H
