// Generated by gencpp from file grinder_chassis_driver/ChassisStatus.msg
// DO NOT EDIT!


#ifndef GRINDER_CHASSIS_DRIVER_MESSAGE_CHASSISSTATUS_H
#define GRINDER_CHASSIS_DRIVER_MESSAGE_CHASSISSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace grinder_chassis_driver
{
template <class ContainerAllocator>
struct ChassisStatus_
{
  typedef ChassisStatus_<ContainerAllocator> Type;

  ChassisStatus_()
    : header()
    , connected(false)
    , enabled(false)
    , work_mode(0)
    , disc_speed_target(0)
    , disc_speed_feedback(0)
    , disc_enabled(false)
    , disc_lift_state(0)
    , light_enabled(false)
    , consecutive_failures(0)
    , last_error()  {
    }
  ChassisStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , connected(false)
    , enabled(false)
    , work_mode(0)
    , disc_speed_target(0)
    , disc_speed_feedback(0)
    , disc_enabled(false)
    , disc_lift_state(0)
    , light_enabled(false)
    , consecutive_failures(0)
    , last_error(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _connected_type;
  _connected_type connected;

   typedef uint8_t _enabled_type;
  _enabled_type enabled;

   typedef uint16_t _work_mode_type;
  _work_mode_type work_mode;

   typedef int16_t _disc_speed_target_type;
  _disc_speed_target_type disc_speed_target;

   typedef int16_t _disc_speed_feedback_type;
  _disc_speed_feedback_type disc_speed_feedback;

   typedef uint8_t _disc_enabled_type;
  _disc_enabled_type disc_enabled;

   typedef uint16_t _disc_lift_state_type;
  _disc_lift_state_type disc_lift_state;

   typedef uint8_t _light_enabled_type;
  _light_enabled_type light_enabled;

   typedef uint32_t _consecutive_failures_type;
  _consecutive_failures_type consecutive_failures;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _last_error_type;
  _last_error_type last_error;





  typedef boost::shared_ptr< ::grinder_chassis_driver::ChassisStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grinder_chassis_driver::ChassisStatus_<ContainerAllocator> const> ConstPtr;

}; // struct ChassisStatus_

typedef ::grinder_chassis_driver::ChassisStatus_<std::allocator<void> > ChassisStatus;

typedef boost::shared_ptr< ::grinder_chassis_driver::ChassisStatus > ChassisStatusPtr;
typedef boost::shared_ptr< ::grinder_chassis_driver::ChassisStatus const> ChassisStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grinder_chassis_driver::ChassisStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grinder_chassis_driver::ChassisStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::grinder_chassis_driver::ChassisStatus_<ContainerAllocator1> & lhs, const ::grinder_chassis_driver::ChassisStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.connected == rhs.connected &&
    lhs.enabled == rhs.enabled &&
    lhs.work_mode == rhs.work_mode &&
    lhs.disc_speed_target == rhs.disc_speed_target &&
    lhs.disc_speed_feedback == rhs.disc_speed_feedback &&
    lhs.disc_enabled == rhs.disc_enabled &&
    lhs.disc_lift_state == rhs.disc_lift_state &&
    lhs.light_enabled == rhs.light_enabled &&
    lhs.consecutive_failures == rhs.consecutive_failures &&
    lhs.last_error == rhs.last_error;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::grinder_chassis_driver::ChassisStatus_<ContainerAllocator1> & lhs, const ::grinder_chassis_driver::ChassisStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace grinder_chassis_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::grinder_chassis_driver::ChassisStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grinder_chassis_driver::ChassisStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grinder_chassis_driver::ChassisStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grinder_chassis_driver::ChassisStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grinder_chassis_driver::ChassisStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grinder_chassis_driver::ChassisStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grinder_chassis_driver::ChassisStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "332527d3d7aab4589bcc1f2c43bb82d4";
  }

  static const char* value(const ::grinder_chassis_driver::ChassisStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x332527d3d7aab458ULL;
  static const uint64_t static_value2 = 0x9bcc1f2c43bb82d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::grinder_chassis_driver::ChassisStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grinder_chassis_driver/ChassisStatus";
  }

  static const char* value(const ::grinder_chassis_driver::ChassisStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grinder_chassis_driver::ChassisStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"bool connected\n"
"bool enabled\n"
"uint16 work_mode\n"
"int16 disc_speed_target\n"
"int16 disc_speed_feedback\n"
"bool disc_enabled\n"
"uint16 disc_lift_state\n"
"bool light_enabled\n"
"uint32 consecutive_failures\n"
"string last_error\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::grinder_chassis_driver::ChassisStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grinder_chassis_driver::ChassisStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.connected);
      stream.next(m.enabled);
      stream.next(m.work_mode);
      stream.next(m.disc_speed_target);
      stream.next(m.disc_speed_feedback);
      stream.next(m.disc_enabled);
      stream.next(m.disc_lift_state);
      stream.next(m.light_enabled);
      stream.next(m.consecutive_failures);
      stream.next(m.last_error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChassisStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grinder_chassis_driver::ChassisStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grinder_chassis_driver::ChassisStatus_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "connected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.connected);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "enabled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enabled);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "work_mode: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.work_mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "disc_speed_target: ";
    Printer<int16_t>::stream(s, indent + "  ", v.disc_speed_target);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "disc_speed_feedback: ";
    Printer<int16_t>::stream(s, indent + "  ", v.disc_speed_feedback);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "disc_enabled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.disc_enabled);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "disc_lift_state: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.disc_lift_state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "light_enabled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.light_enabled);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "consecutive_failures: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.consecutive_failures);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "last_error: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.last_error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRINDER_CHASSIS_DRIVER_MESSAGE_CHASSISSTATUS_H
