// Generated by gencpp from file grinder_chassis_driver/ClearFault.msg
// DO NOT EDIT!


#ifndef GRINDER_CHASSIS_DRIVER_MESSAGE_CLEARFAULT_H
#define GRINDER_CHASSIS_DRIVER_MESSAGE_CLEARFAULT_H

#include <ros/service_traits.h>


#include <grinder_chassis_driver/ClearFaultRequest.h>
#include <grinder_chassis_driver/ClearFaultResponse.h>


namespace grinder_chassis_driver
{

struct ClearFault
{

typedef ClearFaultRequest Request;
typedef ClearFaultResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClearFault
} // namespace grinder_chassis_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::grinder_chassis_driver::ClearFault > {
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::grinder_chassis_driver::ClearFault&) { return value(); }
};

template<>
struct DataType< ::grinder_chassis_driver::ClearFault > {
  static const char* value()
  {
    return "grinder_chassis_driver/ClearFault";
  }

  static const char* value(const ::grinder_chassis_driver::ClearFault&) { return value(); }
};


// service_traits::MD5Sum< ::grinder_chassis_driver::ClearFaultRequest> should match
// service_traits::MD5Sum< ::grinder_chassis_driver::ClearFault >
template<>
struct MD5Sum< ::grinder_chassis_driver::ClearFaultRequest>
{
  static const char* value()
  {
    return MD5Sum< ::grinder_chassis_driver::ClearFault >::value();
  }
  static const char* value(const ::grinder_chassis_driver::ClearFaultRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::grinder_chassis_driver::ClearFaultRequest> should match
// service_traits::DataType< ::grinder_chassis_driver::ClearFault >
template<>
struct DataType< ::grinder_chassis_driver::ClearFaultRequest>
{
  static const char* value()
  {
    return DataType< ::grinder_chassis_driver::ClearFault >::value();
  }
  static const char* value(const ::grinder_chassis_driver::ClearFaultRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::grinder_chassis_driver::ClearFaultResponse> should match
// service_traits::MD5Sum< ::grinder_chassis_driver::ClearFault >
template<>
struct MD5Sum< ::grinder_chassis_driver::ClearFaultResponse>
{
  static const char* value()
  {
    return MD5Sum< ::grinder_chassis_driver::ClearFault >::value();
  }
  static const char* value(const ::grinder_chassis_driver::ClearFaultResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::grinder_chassis_driver::ClearFaultResponse> should match
// service_traits::DataType< ::grinder_chassis_driver::ClearFault >
template<>
struct DataType< ::grinder_chassis_driver::ClearFaultResponse>
{
  static const char* value()
  {
    return DataType< ::grinder_chassis_driver::ClearFault >::value();
  }
  static const char* value(const ::grinder_chassis_driver::ClearFaultResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRINDER_CHASSIS_DRIVER_MESSAGE_CLEARFAULT_H
