// Generated by gencpp from file grinder_chassis_driver/ClearFaultResponse.msg
// DO NOT EDIT!


#ifndef GRINDER_CHASSIS_DRIVER_MESSAGE_CLEARFAULTRESPONSE_H
#define GRINDER_CHASSIS_DRIVER_MESSAGE_CLEARFAULTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace grinder_chassis_driver
{
template <class ContainerAllocator>
struct ClearFaultResponse_
{
  typedef ClearFaultResponse_<ContainerAllocator> Type;

  ClearFaultResponse_()
    : success(false)
    , message()  {
    }
  ClearFaultResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::grinder_chassis_driver::ClearFaultResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grinder_chassis_driver::ClearFaultResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ClearFaultResponse_

typedef ::grinder_chassis_driver::ClearFaultResponse_<std::allocator<void> > ClearFaultResponse;

typedef boost::shared_ptr< ::grinder_chassis_driver::ClearFaultResponse > ClearFaultResponsePtr;
typedef boost::shared_ptr< ::grinder_chassis_driver::ClearFaultResponse const> ClearFaultResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grinder_chassis_driver::ClearFaultResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grinder_chassis_driver::ClearFaultResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::grinder_chassis_driver::ClearFaultResponse_<ContainerAllocator1> & lhs, const ::grinder_chassis_driver::ClearFaultResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::grinder_chassis_driver::ClearFaultResponse_<ContainerAllocator1> & lhs, const ::grinder_chassis_driver::ClearFaultResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace grinder_chassis_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::grinder_chassis_driver::ClearFaultResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grinder_chassis_driver::ClearFaultResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grinder_chassis_driver::ClearFaultResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grinder_chassis_driver::ClearFaultResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grinder_chassis_driver::ClearFaultResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grinder_chassis_driver::ClearFaultResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grinder_chassis_driver::ClearFaultResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::grinder_chassis_driver::ClearFaultResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::grinder_chassis_driver::ClearFaultResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grinder_chassis_driver/ClearFaultResponse";
  }

  static const char* value(const ::grinder_chassis_driver::ClearFaultResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grinder_chassis_driver::ClearFaultResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::grinder_chassis_driver::ClearFaultResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grinder_chassis_driver::ClearFaultResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClearFaultResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grinder_chassis_driver::ClearFaultResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grinder_chassis_driver::ClearFaultResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRINDER_CHASSIS_DRIVER_MESSAGE_CLEARFAULTRESPONSE_H
