// Generated by gencpp from file grinder_chassis_driver/ClearFaultRequest.msg
// DO NOT EDIT!


#ifndef GRINDER_CHASSIS_DRIVER_MESSAGE_CLEARFAULTREQUEST_H
#define GRINDER_CHASSIS_DRIVER_MESSAGE_CLEARFAULTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace grinder_chassis_driver
{
template <class ContainerAllocator>
struct ClearFaultRequest_
{
  typedef ClearFaultRequest_<ContainerAllocator> Type;

  ClearFaultRequest_()
    {
    }
  ClearFaultRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::grinder_chassis_driver::ClearFaultRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grinder_chassis_driver::ClearFaultRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ClearFaultRequest_

typedef ::grinder_chassis_driver::ClearFaultRequest_<std::allocator<void> > ClearFaultRequest;

typedef boost::shared_ptr< ::grinder_chassis_driver::ClearFaultRequest > ClearFaultRequestPtr;
typedef boost::shared_ptr< ::grinder_chassis_driver::ClearFaultRequest const> ClearFaultRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grinder_chassis_driver::ClearFaultRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grinder_chassis_driver::ClearFaultRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace grinder_chassis_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::grinder_chassis_driver::ClearFaultRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grinder_chassis_driver::ClearFaultRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grinder_chassis_driver::ClearFaultRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grinder_chassis_driver::ClearFaultRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grinder_chassis_driver::ClearFaultRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grinder_chassis_driver::ClearFaultRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grinder_chassis_driver::ClearFaultRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::grinder_chassis_driver::ClearFaultRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::grinder_chassis_driver::ClearFaultRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grinder_chassis_driver/ClearFaultRequest";
  }

  static const char* value(const ::grinder_chassis_driver::ClearFaultRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grinder_chassis_driver::ClearFaultRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::grinder_chassis_driver::ClearFaultRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grinder_chassis_driver::ClearFaultRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClearFaultRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grinder_chassis_driver::ClearFaultRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::grinder_chassis_driver::ClearFaultRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // GRINDER_CHASSIS_DRIVER_MESSAGE_CLEARFAULTREQUEST_H
