// Generated by gencpp from file grinder_chassis_driver/EnableChassisRequest.msg
// DO NOT EDIT!


#ifndef GRINDER_CHASSIS_DRIVER_MESSAGE_ENABLECHASSISREQUEST_H
#define GRINDER_CHASSIS_DRIVER_MESSAGE_ENABLECHASSISREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace grinder_chassis_driver
{
template <class ContainerAllocator>
struct EnableChassisRequest_
{
  typedef EnableChassisRequest_<ContainerAllocator> Type;

  EnableChassisRequest_()
    : enable(false)  {
    }
  EnableChassisRequest_(const ContainerAllocator& _alloc)
    : enable(false)  {
  (void)_alloc;
    }



   typedef uint8_t _enable_type;
  _enable_type enable;





  typedef boost::shared_ptr< ::grinder_chassis_driver::EnableChassisRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grinder_chassis_driver::EnableChassisRequest_<ContainerAllocator> const> ConstPtr;

}; // struct EnableChassisRequest_

typedef ::grinder_chassis_driver::EnableChassisRequest_<std::allocator<void> > EnableChassisRequest;

typedef boost::shared_ptr< ::grinder_chassis_driver::EnableChassisRequest > EnableChassisRequestPtr;
typedef boost::shared_ptr< ::grinder_chassis_driver::EnableChassisRequest const> EnableChassisRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grinder_chassis_driver::EnableChassisRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grinder_chassis_driver::EnableChassisRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::grinder_chassis_driver::EnableChassisRequest_<ContainerAllocator1> & lhs, const ::grinder_chassis_driver::EnableChassisRequest_<ContainerAllocator2> & rhs)
{
  return lhs.enable == rhs.enable;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::grinder_chassis_driver::EnableChassisRequest_<ContainerAllocator1> & lhs, const ::grinder_chassis_driver::EnableChassisRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace grinder_chassis_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::grinder_chassis_driver::EnableChassisRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grinder_chassis_driver::EnableChassisRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grinder_chassis_driver::EnableChassisRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grinder_chassis_driver::EnableChassisRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grinder_chassis_driver::EnableChassisRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grinder_chassis_driver::EnableChassisRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grinder_chassis_driver::EnableChassisRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8c1211af706069c994c06e00eb59ac9e";
  }

  static const char* value(const ::grinder_chassis_driver::EnableChassisRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8c1211af706069c9ULL;
  static const uint64_t static_value2 = 0x94c06e00eb59ac9eULL;
};

template<class ContainerAllocator>
struct DataType< ::grinder_chassis_driver::EnableChassisRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grinder_chassis_driver/EnableChassisRequest";
  }

  static const char* value(const ::grinder_chassis_driver::EnableChassisRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grinder_chassis_driver::EnableChassisRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool enable\n"
;
  }

  static const char* value(const ::grinder_chassis_driver::EnableChassisRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grinder_chassis_driver::EnableChassisRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enable);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EnableChassisRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grinder_chassis_driver::EnableChassisRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grinder_chassis_driver::EnableChassisRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRINDER_CHASSIS_DRIVER_MESSAGE_ENABLECHASSISREQUEST_H
