// Generated by gencpp from file grinder_chassis_driver/EnableChassis.msg
// DO NOT EDIT!


#ifndef GRINDER_CHASSIS_DRIVER_MESSAGE_ENABLECHASSIS_H
#define GRINDER_CHASSIS_DRIVER_MESSAGE_ENABLECHASSIS_H

#include <ros/service_traits.h>


#include <grinder_chassis_driver/EnableChassisRequest.h>
#include <grinder_chassis_driver/EnableChassisResponse.h>


namespace grinder_chassis_driver
{

struct EnableChassis
{

typedef EnableChassisRequest Request;
typedef EnableChassisResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EnableChassis
} // namespace grinder_chassis_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::grinder_chassis_driver::EnableChassis > {
  static const char* value()
  {
    return "66bc8d9da0bd59298d38df02f3ee7f7f";
  }

  static const char* value(const ::grinder_chassis_driver::EnableChassis&) { return value(); }
};

template<>
struct DataType< ::grinder_chassis_driver::EnableChassis > {
  static const char* value()
  {
    return "grinder_chassis_driver/EnableChassis";
  }

  static const char* value(const ::grinder_chassis_driver::EnableChassis&) { return value(); }
};


// service_traits::MD5Sum< ::grinder_chassis_driver::EnableChassisRequest> should match
// service_traits::MD5Sum< ::grinder_chassis_driver::EnableChassis >
template<>
struct MD5Sum< ::grinder_chassis_driver::EnableChassisRequest>
{
  static const char* value()
  {
    return MD5Sum< ::grinder_chassis_driver::EnableChassis >::value();
  }
  static const char* value(const ::grinder_chassis_driver::EnableChassisRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::grinder_chassis_driver::EnableChassisRequest> should match
// service_traits::DataType< ::grinder_chassis_driver::EnableChassis >
template<>
struct DataType< ::grinder_chassis_driver::EnableChassisRequest>
{
  static const char* value()
  {
    return DataType< ::grinder_chassis_driver::EnableChassis >::value();
  }
  static const char* value(const ::grinder_chassis_driver::EnableChassisRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::grinder_chassis_driver::EnableChassisResponse> should match
// service_traits::MD5Sum< ::grinder_chassis_driver::EnableChassis >
template<>
struct MD5Sum< ::grinder_chassis_driver::EnableChassisResponse>
{
  static const char* value()
  {
    return MD5Sum< ::grinder_chassis_driver::EnableChassis >::value();
  }
  static const char* value(const ::grinder_chassis_driver::EnableChassisResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::grinder_chassis_driver::EnableChassisResponse> should match
// service_traits::DataType< ::grinder_chassis_driver::EnableChassis >
template<>
struct DataType< ::grinder_chassis_driver::EnableChassisResponse>
{
  static const char* value()
  {
    return DataType< ::grinder_chassis_driver::EnableChassis >::value();
  }
  static const char* value(const ::grinder_chassis_driver::EnableChassisResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRINDER_CHASSIS_DRIVER_MESSAGE_ENABLECHASSIS_H
