// Generated by gencpp from file grinder_chassis_driver/WheelSpeedState.msg
// DO NOT EDIT!


#ifndef GRINDER_CHASSIS_DRIVER_MESSAGE_WHEELSPEEDSTATE_H
#define GRINDER_CHASSIS_DRIVER_MESSAGE_WHEELSPEEDSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace grinder_chassis_driver
{
template <class ContainerAllocator>
struct WheelSpeedState_
{
  typedef WheelSpeedState_<ContainerAllocator> Type;

  WheelSpeedState_()
    : header()
    , target_left_wheel_speed(0)
    , target_right_wheel_speed(0)
    , feedback_left_wheel_speed(0)
    , feedback_right_wheel_speed(0)
    , feedback_valid(false)  {
    }
  WheelSpeedState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , target_left_wheel_speed(0)
    , target_right_wheel_speed(0)
    , feedback_left_wheel_speed(0)
    , feedback_right_wheel_speed(0)
    , feedback_valid(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _target_left_wheel_speed_type;
  _target_left_wheel_speed_type target_left_wheel_speed;

   typedef int16_t _target_right_wheel_speed_type;
  _target_right_wheel_speed_type target_right_wheel_speed;

   typedef int16_t _feedback_left_wheel_speed_type;
  _feedback_left_wheel_speed_type feedback_left_wheel_speed;

   typedef int16_t _feedback_right_wheel_speed_type;
  _feedback_right_wheel_speed_type feedback_right_wheel_speed;

   typedef uint8_t _feedback_valid_type;
  _feedback_valid_type feedback_valid;





  typedef boost::shared_ptr< ::grinder_chassis_driver::WheelSpeedState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grinder_chassis_driver::WheelSpeedState_<ContainerAllocator> const> ConstPtr;

}; // struct WheelSpeedState_

typedef ::grinder_chassis_driver::WheelSpeedState_<std::allocator<void> > WheelSpeedState;

typedef boost::shared_ptr< ::grinder_chassis_driver::WheelSpeedState > WheelSpeedStatePtr;
typedef boost::shared_ptr< ::grinder_chassis_driver::WheelSpeedState const> WheelSpeedStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grinder_chassis_driver::WheelSpeedState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grinder_chassis_driver::WheelSpeedState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::grinder_chassis_driver::WheelSpeedState_<ContainerAllocator1> & lhs, const ::grinder_chassis_driver::WheelSpeedState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.target_left_wheel_speed == rhs.target_left_wheel_speed &&
    lhs.target_right_wheel_speed == rhs.target_right_wheel_speed &&
    lhs.feedback_left_wheel_speed == rhs.feedback_left_wheel_speed &&
    lhs.feedback_right_wheel_speed == rhs.feedback_right_wheel_speed &&
    lhs.feedback_valid == rhs.feedback_valid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::grinder_chassis_driver::WheelSpeedState_<ContainerAllocator1> & lhs, const ::grinder_chassis_driver::WheelSpeedState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace grinder_chassis_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::grinder_chassis_driver::WheelSpeedState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grinder_chassis_driver::WheelSpeedState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grinder_chassis_driver::WheelSpeedState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grinder_chassis_driver::WheelSpeedState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grinder_chassis_driver::WheelSpeedState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grinder_chassis_driver::WheelSpeedState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grinder_chassis_driver::WheelSpeedState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f50663abf771ecfd2d1486cfc892cbc3";
  }

  static const char* value(const ::grinder_chassis_driver::WheelSpeedState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf50663abf771ecfdULL;
  static const uint64_t static_value2 = 0x2d1486cfc892cbc3ULL;
};

template<class ContainerAllocator>
struct DataType< ::grinder_chassis_driver::WheelSpeedState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grinder_chassis_driver/WheelSpeedState";
  }

  static const char* value(const ::grinder_chassis_driver::WheelSpeedState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grinder_chassis_driver::WheelSpeedState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"int16 target_left_wheel_speed\n"
"int16 target_right_wheel_speed\n"
"int16 feedback_left_wheel_speed\n"
"int16 feedback_right_wheel_speed\n"
"bool feedback_valid\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::grinder_chassis_driver::WheelSpeedState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grinder_chassis_driver::WheelSpeedState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.target_left_wheel_speed);
      stream.next(m.target_right_wheel_speed);
      stream.next(m.feedback_left_wheel_speed);
      stream.next(m.feedback_right_wheel_speed);
      stream.next(m.feedback_valid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WheelSpeedState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grinder_chassis_driver::WheelSpeedState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grinder_chassis_driver::WheelSpeedState_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_left_wheel_speed: ";
    Printer<int16_t>::stream(s, indent + "  ", v.target_left_wheel_speed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target_right_wheel_speed: ";
    Printer<int16_t>::stream(s, indent + "  ", v.target_right_wheel_speed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "feedback_left_wheel_speed: ";
    Printer<int16_t>::stream(s, indent + "  ", v.feedback_left_wheel_speed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "feedback_right_wheel_speed: ";
    Printer<int16_t>::stream(s, indent + "  ", v.feedback_right_wheel_speed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "feedback_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.feedback_valid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRINDER_CHASSIS_DRIVER_MESSAGE_WHEELSPEEDSTATE_H
