// Generated by gencpp from file grinder_chassis_driver/WheelSpeedCommand.msg
// DO NOT EDIT!


#ifndef GRINDER_CHASSIS_DRIVER_MESSAGE_WHEELSPEEDCOMMAND_H
#define GRINDER_CHASSIS_DRIVER_MESSAGE_WHEELSPEEDCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace grinder_chassis_driver
{
template <class ContainerAllocator>
struct WheelSpeedCommand_
{
  typedef WheelSpeedCommand_<ContainerAllocator> Type;

  WheelSpeedCommand_()
    : left_wheel_speed(0)
    , right_wheel_speed(0)  {
    }
  WheelSpeedCommand_(const ContainerAllocator& _alloc)
    : left_wheel_speed(0)
    , right_wheel_speed(0)  {
  (void)_alloc;
    }



   typedef int16_t _left_wheel_speed_type;
  _left_wheel_speed_type left_wheel_speed;

   typedef int16_t _right_wheel_speed_type;
  _right_wheel_speed_type right_wheel_speed;





  typedef boost::shared_ptr< ::grinder_chassis_driver::WheelSpeedCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::grinder_chassis_driver::WheelSpeedCommand_<ContainerAllocator> const> ConstPtr;

}; // struct WheelSpeedCommand_

typedef ::grinder_chassis_driver::WheelSpeedCommand_<std::allocator<void> > WheelSpeedCommand;

typedef boost::shared_ptr< ::grinder_chassis_driver::WheelSpeedCommand > WheelSpeedCommandPtr;
typedef boost::shared_ptr< ::grinder_chassis_driver::WheelSpeedCommand const> WheelSpeedCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::grinder_chassis_driver::WheelSpeedCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::grinder_chassis_driver::WheelSpeedCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::grinder_chassis_driver::WheelSpeedCommand_<ContainerAllocator1> & lhs, const ::grinder_chassis_driver::WheelSpeedCommand_<ContainerAllocator2> & rhs)
{
  return lhs.left_wheel_speed == rhs.left_wheel_speed &&
    lhs.right_wheel_speed == rhs.right_wheel_speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::grinder_chassis_driver::WheelSpeedCommand_<ContainerAllocator1> & lhs, const ::grinder_chassis_driver::WheelSpeedCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace grinder_chassis_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::grinder_chassis_driver::WheelSpeedCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::grinder_chassis_driver::WheelSpeedCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grinder_chassis_driver::WheelSpeedCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::grinder_chassis_driver::WheelSpeedCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grinder_chassis_driver::WheelSpeedCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::grinder_chassis_driver::WheelSpeedCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::grinder_chassis_driver::WheelSpeedCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7c95657b2cfd28ae6e5771e00b505bd4";
  }

  static const char* value(const ::grinder_chassis_driver::WheelSpeedCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7c95657b2cfd28aeULL;
  static const uint64_t static_value2 = 0x6e5771e00b505bd4ULL;
};

template<class ContainerAllocator>
struct DataType< ::grinder_chassis_driver::WheelSpeedCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "grinder_chassis_driver/WheelSpeedCommand";
  }

  static const char* value(const ::grinder_chassis_driver::WheelSpeedCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::grinder_chassis_driver::WheelSpeedCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 left_wheel_speed\n"
"int16 right_wheel_speed\n"
;
  }

  static const char* value(const ::grinder_chassis_driver::WheelSpeedCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::grinder_chassis_driver::WheelSpeedCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_wheel_speed);
      stream.next(m.right_wheel_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WheelSpeedCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::grinder_chassis_driver::WheelSpeedCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::grinder_chassis_driver::WheelSpeedCommand_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "left_wheel_speed: ";
    Printer<int16_t>::stream(s, indent + "  ", v.left_wheel_speed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "right_wheel_speed: ";
    Printer<int16_t>::stream(s, indent + "  ", v.right_wheel_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRINDER_CHASSIS_DRIVER_MESSAGE_WHEELSPEEDCOMMAND_H
